name: Build & Lint & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Auth token set
      #   run: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.PKG_ACCESS_TOKEN }}
      #   run: npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Test the project
        run: npm run test

      - name: Build the project
        run: npm run build
